JavaScript
Nehir0109/basketball-scoreboard pull request #1
Opened 2023-05-30 11:55 UTC by Nehir0109

2023-05-30 11:59 UTC, atul-melorra approved these changes

2023-05-31 16:18 UTC, alperenustun requested changes

2023-05-31 16:18 UTC, alperenustun commented on index.css
> +    width: 149px;
- [ ] burada width'i kaldırman gerekiyor

2023-05-31 16:18 UTC, alperenustun commented on index.css
> +    width: 155px;
- [ ] burada da width'i kaldırmalısın

2023-05-31 16:18 UTC, alperenustun commented on index.html
> +                    <span onclick="incrementHomeOne()" class="increment-button">+1</span>
Bunları daha önceki gibi tek fonksiyonda toplasan daha iyi olurdu 😅

2023-06-04 12:41 UTC, merged